site_name: Daniel Chu
# site_description: [blabla]
site_author: Daniel Chu
# site_url: [link]

copyright: Copyright &copy; 2022 Daniel Chu

theme: 
  name: material
  language: en
  features:
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/catcrumpet
    # - icon: fontawesome/brands/linkedin
    #   link: [linkedin]
    # - icon: fontawesome/solid/paper-plane
    #   link: [email]
  generator: false

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - tables
  - toc:
      permalink: true

  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  #   alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  # for mathjax
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # for tablesort
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

nav:
  - Home: index.md
  - Curriculum Vitae: cv.md
  # - Research:
  #   - "A paper": research/a-paper.md
  # - Software:
  #   - "Software": link-to-software.md
  # - Tutorials:
  #   - "A tutorial": tutorial/a-tutorial.md
  # - Collaborators: collaborators.md